// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with `Firebase.initializeApp()`.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzwEy3dNe4vlio77Td5PvuHYBBGpc4Q8I',
    appId: '1:760296893594:web:0e6ccb429b461d9e6fc323',
    messagingSenderId: '760296893594',
    projectId: 'appletech-6b722',
    authDomain: 'appletech-6b722.firebaseapp.com',
    storageBucket: 'appletech-6b722.firebasestorage.app',
    measurementId: 'G-96M7TED460',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzwEy3dNe4vlio77Td5PvuHYBBGpc4Q8I',
    appId: '1:760296893594:android:c0949ba4a0f2d9306fc323',
    messagingSenderId: '760296893594',
    projectId: 'appletech-6b722',
    storageBucket: 'appletech-6b722.firebasestorage.app',
  );
}
